### ISSUE TITLE
if i use the spawn command i go underground (under the spawn)

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun-magichet#16]
![screenshot_20150911_135726](https://cloud.githubusercontent.com/assets/11613522/9814306/22b44ac6-588d-11e5-811c-d4636cd27c02.png)

**Comment by Ombridride** [comment]
Ok, thank you for the report.

We need to set the spawn point properly, maybe makes a y+1,5 ?

**Comment by Ombridride** [comment]
Assignee @4aiman because it's an Upstream issue and he is the best dev to fix it because he knows the mods better than us

**Comment by 4aiman** [comment]
You have a static_spawn_point set, don't you?

**Comment by Ombridride** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun-magichet/commit/c13be12c38fa6dcf24c8e520e4d23874f43937c1
