### ISSUE TITLE
This animal is immortal

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun-magichet#19]
![screenshot_20150911_222203](https://cloud.githubusercontent.com/assets/11613522/9825445/a12a60e8-58d3-11e5-9edb-70cc62ae4e8a.png)

PS: it's a pig or what ?

**Comment by LeMagnesium** [comment]
It's lag. You killed it but the engine is slowed down and doesn't respond instantly.

**Comment by Ombridride** [comment]
Not a bug but a lag. closed the issue.

**Comment by ObaniGemini** [comment]
Actually, killing a pig makes crash the server (I tried two times and it made crash)
