### ISSUE TITLE
killing a pig crash the server

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun-magichet#26]
Initialy reported from @ObaniGemini 

Actually, killing a pig makes crash the server (I tried two times and it made crash)

**Comment by LeMagnesium** [comment]
I killed an army of pigs with 0.4.13 clients & server and dev clients and server, I can't reproduce it.

**Comment by Ombridride** [comment]
Assignee @4aiman because it's an Upstream issue and he is the best dev to fix it because he knows the mods better than us

**Comment by Ombridride** [comment]
Well seen, thank you for the fix
