### ISSUE TITLE
Add [whoison] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun-magichet#5]
We need to add the [whoison] mod because it's needed for monitoring the number of players online :)

**Comment by 4aiman** [comment]
If you need monitoring only, then ```#minetest.get_connected_players()``` is what you need ;)

**Comment by fabienwang** [comment]
whoison adds functionalities like /seen <user> (last seen datetime)
and /timeonline (cumulative time a player have been connected)
i vote for :+1:

**Comment by 4aiman** [comment]
:+1:  then
Can I have a link to the mod in question?

**Comment by Ombridride** [comment]
we have already this mod on our other servers, you can find the mod here for example https://github.com/MinetestForFun/server-minetestforfun/tree/master/mods/whoison
