### ISSUE TITLE
Add the mapfix mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/server-minetestforfun-magichet#6]
We need to add the mapfix mod, it's a very small mod but a very useful mod, it erase the black shadow on the map (created often by the worldedit mod)

**Comment by 4aiman** [comment]
Is this needed to "fix" WE lighting bug only or it is being called automatically?

**Comment by Ombridride** [comment]
No automatically called, but if we use WE and seems the shadow bugs, we will do a /mapfix for fix it
